package GUIs;

import Controllers.DatabaseDriver;
import Controllers.FrameController;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rgalo
 */
public class LearnersTableGUI extends javax.swing.JFrame {

    /**
     * Creates new form ContributorsGUI
     */
    public LearnersTableGUI() {
        initComponents();
        populateTable();
        FrameController.setLayout(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblContributors = new javax.swing.JScrollPane();
        tblEntries = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        btnEnroll = new javax.swing.JButton();
        btnLearners = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnDetentions = new javax.swing.JButton();
        txfFName = new javax.swing.JTextField();
        txfSurname = new javax.swing.JTextField();
        txfGrade = new javax.swing.JTextField();
        btnUnenroll = new javax.swing.JButton();
        txfEnroll = new javax.swing.JTextField();
        txfGrade2 = new javax.swing.JTextField();
        txfGrade3 = new javax.swing.JTextField();
        txfGrade5 = new javax.swing.JTextField();
        txfGrade6 = new javax.swing.JTextField();
        txfGrade7 = new javax.swing.JTextField();
        txfGrade8 = new javax.swing.JTextField();
        txfGrade9 = new javax.swing.JTextField();
        txfGrade10 = new javax.swing.JTextField();
        btnIndividually1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEntries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Grade", "Enrolled", "P First Name", "P Last Name", "P Email", "P Cell", "S First Name", "S Last Name", "S Email", "S Cell"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEntries.setRowHeight(25);
        tblContributors.setViewportView(tblEntries);

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTitle.setText("Learners");

        btnEnroll.setText("Enroll Learner");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });

        btnLearners.setText("Learners");
        btnLearners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLearnersActionPerformed(evt);
            }
        });

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnDetentions.setText("Detentions");
        btnDetentions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetentionsActionPerformed(evt);
            }
        });

        txfFName.setText("First Name");
        txfFName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfFNameFocusGained(evt);
            }
        });
        txfFName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfFNameMouseClicked(evt);
            }
        });

        txfSurname.setText("Last Name");
        txfSurname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfSurnameFocusGained(evt);
            }
        });
        txfSurname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfSurnameMouseClicked(evt);
            }
        });

        txfGrade.setText("Grade");
        txfGrade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfGradeFocusGained(evt);
            }
        });
        txfGrade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfGradeKeyTyped(evt);
            }
        });

        btnUnenroll.setText("Unenroll Learner");
        btnUnenroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnenrollActionPerformed(evt);
            }
        });

        txfEnroll.setText("Enrolled");
        txfEnroll.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfEnrollFocusGained(evt);
            }
        });

        txfGrade2.setText("P First Name");
        txfGrade2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfGrade2FocusGained(evt);
            }
        });
        txfGrade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfGrade2ActionPerformed(evt);
            }
        });

        txfGrade3.setText("P Last Name");
        txfGrade3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfGrade3FocusGained(evt);
            }
        });
        txfGrade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfGrade3ActionPerformed(evt);
            }
        });

        txfGrade5.setText("P Email");
        txfGrade5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfGrade5FocusGained(evt);
            }
        });
        txfGrade5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfGrade5ActionPerformed(evt);
            }
        });

        txfGrade6.setText("P Cell");
        txfGrade6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfGrade6FocusGained(evt);
            }
        });

        txfGrade7.setText("S First Name");
        txfGrade7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfGrade7FocusGained(evt);
            }
        });

        txfGrade8.setText("S Last Name");
        txfGrade8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfGrade8FocusGained(evt);
            }
        });
        txfGrade8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfGrade8ActionPerformed(evt);
            }
        });

        txfGrade9.setText("S Email");
        txfGrade9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfGrade9FocusGained(evt);
            }
        });

        txfGrade10.setText("S Cell");
        txfGrade10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txfGrade10FocusGained(evt);
            }
        });
        txfGrade10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfGrade10KeyTyped(evt);
            }
        });

        btnIndividually1.setText("Advance Year");
        btnIndividually1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndividually1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblContributors)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfFName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnLearners, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDetentions, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfGrade2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfGrade3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfGrade5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfGrade6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfGrade7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfGrade8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfGrade9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfGrade10, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnIndividually1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUnenroll, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnLearners)
                    .addComponent(btnDetentions)
                    .addComponent(btnHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblContributors, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfGrade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfGrade3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfGrade5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfGrade6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfGrade7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfGrade8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfGrade9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfGrade10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnroll)
                    .addComponent(btnUnenroll)
                    .addComponent(btnIndividually1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        String fName = txfFName.getText();
        String sName = txfSurname.getText();
        String grade = txfGrade.getText();
        String enroll = txfEnroll.getText();
        String pfn = txfGrade2.getText();
        String psn = txfGrade3.getText();
        String pem = txfGrade5.getText();
        String pce = txfGrade6.getText();
        String sfn = txfGrade7.getText();
        String ssn = txfGrade8.getText();
        String sem = txfGrade9.getText();
        String sce = txfGrade10.getText();
        if (fName.isEmpty() || sName.isEmpty() || grade.isEmpty() || enroll.isEmpty() || pfn.isEmpty() || psn.isEmpty() || pem.isEmpty() || pce.isEmpty() || sfn.isEmpty() || ssn.isEmpty() || sem.isEmpty() || sce.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter details in each of the text fields to the left of the 'Add' Button", "Invalid Input Error", ERROR_MESSAGE);
        } else {
            int c = JOptionPane.showConfirmDialog(null, "Do you want to enroll:\n'" + fName + "', '" + sName + "', " + grade + ", " + enroll + ", '" + pfn + "', '" + psn + "', '" + pem + "', '" + pce + "', '" + sfn + "', '" + ssn + "', '" + sem + "', '" + sce + "'");
            System.out.println(c);
            if (c == 0) {
                String sqlAdd = "INSERT INTO tblLearner( FName, SName, Grade, Enrolled, PFName, PSName, PEmail, PCell, SFName, SSName, SEmail, SCell ) \n"
                        + "VALUES('" + fName + "', '" + sName + "', " + grade + ", " + enroll + ", '" + pfn + "', '" + psn + "', '" + pem + "', '" + pce + "', '" + sfn + "', '" + ssn + "', '" + sem + "', '" + sce + "');";
                boolean insert = DatabaseDriver.insert(sqlAdd);
                System.out.println("Insert : " + insert);
                populateTable();
            }
        }
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void btnLearnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearnersActionPerformed
        dispose();
        LearnersTableGUI ctg = new LearnersTableGUI();
    }//GEN-LAST:event_btnLearnersActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        dispose();
        HomeGUI homeGUI = new HomeGUI();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnDetentionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetentionsActionPerformed
        dispose();
        DetentionsTableGUI dtg = new DetentionsTableGUI();
    }//GEN-LAST:event_btnDetentionsActionPerformed

    private void txfFNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfFNameMouseClicked
        txfFName.setText("");
    }//GEN-LAST:event_txfFNameMouseClicked

    private void txfSurnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfSurnameMouseClicked
        txfSurname.setText("");
    }//GEN-LAST:event_txfSurnameMouseClicked

    private void txfGradeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfGradeFocusGained
        txfGrade.setText("");
    }//GEN-LAST:event_txfGradeFocusGained

    private void txfSurnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfSurnameFocusGained
        txfSurname.setText("");
    }//GEN-LAST:event_txfSurnameFocusGained

    private void txfFNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfFNameFocusGained
        txfFName.setText("");
    }//GEN-LAST:event_txfFNameFocusGained

    private void btnUnenrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnenrollActionPerformed
        String fName = txfFName.getText();
        String sName = txfSurname.getText();
        String grade = txfGrade.getText();
        if (fName.isEmpty() || sName.isEmpty() || grade.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter details in each of the text fields to the left of the 'Add' Button", "Invalid Input Error", ERROR_MESSAGE);
        } else {
            int c = JOptionPane.showConfirmDialog(null, "Are you sure you want to unenroll:\n'" + fName + "', '" + sName + "', " + grade);
            System.out.println(c);
            if (c == 0) {
                String sqlUnenroll = "UPDATE tblLearner SET Enrolled = FALSE\n"
                        + "WHERE FName LIKE '" + fName + "' AND SName LIKE '" + sName + "' AND Grade = " + grade + ";";
                int unenroll = DatabaseDriver.update(sqlUnenroll);
                System.out.println("Unenroll : " + unenroll);
                populateTable();
            }
        }
    }//GEN-LAST:event_btnUnenrollActionPerformed

    private void txfEnrollFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfEnrollFocusGained
        txfEnroll.setText("");
    }//GEN-LAST:event_txfEnrollFocusGained

    private void txfGrade2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfGrade2FocusGained
        txfGrade2.setText("");
    }//GEN-LAST:event_txfGrade2FocusGained

    private void txfGrade3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfGrade3FocusGained
        txfGrade3.setText("");
    }//GEN-LAST:event_txfGrade3FocusGained

    private void txfGrade5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfGrade5FocusGained
        txfGrade5.setText("");
    }//GEN-LAST:event_txfGrade5FocusGained

    private void txfGrade6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfGrade6FocusGained
        txfGrade6.setText("");
    }//GEN-LAST:event_txfGrade6FocusGained

    private void txfGrade7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfGrade7FocusGained
        txfGrade7.setText("");
    }//GEN-LAST:event_txfGrade7FocusGained

    private void txfGrade8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfGrade8FocusGained
        txfGrade8.setText("");
    }//GEN-LAST:event_txfGrade8FocusGained

    private void txfGrade9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfGrade9FocusGained
        txfGrade9.setText("");
    }//GEN-LAST:event_txfGrade9FocusGained

    private void txfGrade10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfGrade10FocusGained
        txfGrade10.setText("");
    }//GEN-LAST:event_txfGrade10FocusGained

    private void txfGrade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfGrade2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfGrade2ActionPerformed

    private void txfGrade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfGrade3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfGrade3ActionPerformed

    private void txfGrade5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfGrade5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfGrade5ActionPerformed

    private void txfGrade8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfGrade8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfGrade8ActionPerformed

    private void btnIndividually1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndividually1ActionPerformed
        int c = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete all the detentions currently stored\nand increment all the learners' grades? This cannot be undone.");
        System.out.println(c);
        switch (c) {
            case 0:
                String sqlAdd = "UPDATE tblLearner SET Grade = Grade+1;";
                int add = DatabaseDriver.update(sqlAdd);
                System.out.println("Grade+1 : " + add);
                String sqlUnenrollMatrix = "UPDATE tblLearner SET Enrolled = FALSE WHERE Grade = 13;";
                int unenroll = DatabaseDriver.update(sqlUnenrollMatrix);
                System.out.println("Unenroll grade 13: " + unenroll);
                String delDetentions = "DELETE * FROM tblDetention;";
                int delDetnentionResult = DatabaseDriver.update(delDetentions);
                System.out.println("Unenroll grade 13: " + delDetnentionResult);
                break;
            default:
                break;
        }
        populateTable();
    }//GEN-LAST:event_btnIndividually1ActionPerformed

    private void txfGrade10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfGrade10KeyTyped

    }//GEN-LAST:event_txfGrade10KeyTyped

    private void txfGradeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfGradeKeyTyped

    }//GEN-LAST:event_txfGradeKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetentions;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnIndividually1;
    private javax.swing.JButton btnLearners;
    private javax.swing.JButton btnUnenroll;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane tblContributors;
    private javax.swing.JTable tblEntries;
    private javax.swing.JTextField txfEnroll;
    private javax.swing.JTextField txfFName;
    private javax.swing.JTextField txfGrade;
    private javax.swing.JTextField txfGrade10;
    private javax.swing.JTextField txfGrade2;
    private javax.swing.JTextField txfGrade3;
    private javax.swing.JTextField txfGrade5;
    private javax.swing.JTextField txfGrade6;
    private javax.swing.JTextField txfGrade7;
    private javax.swing.JTextField txfGrade8;
    private javax.swing.JTextField txfGrade9;
    private javax.swing.JTextField txfSurname;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        try {
            String sqlStatement = "SELECT FName, SName, Grade, Enrolled, PFName, PSName, PEmail, PCell, SFName, SSName, SEmail, SCell\n"
                    + "FROM tblLearner\n"
                    + "WHERE Enrolled = TRUE\n"
                    + "ORDER BY Grade DESC, SName DESC, FName DESC;";
            ResultSet rs = DatabaseDriver.query(sqlStatement);
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();

            Vector<Vector<Object>> dataInVector = new Vector<>();
            while (rs.next()) {

                Vector<Object> vector = new Vector<>();
                for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                    vector.add("" + rs.getObject(columnIndex));
                }
                dataInVector.add(vector);
            }

            DefaultTableModel dtm = (DefaultTableModel) tblEntries.getModel();
            dtm.setRowCount(0);
            Iterator<Vector<Object>> iterator = dataInVector.iterator();
            while (iterator.hasNext()) {
                Vector<Object> currentRecord = (Vector<Object>) iterator.next();
                dtm.insertRow(0, currentRecord);
            }
        } catch (SQLException ex) {
            Logger.getLogger(LearnersTableGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
